openapi: 3.0.3
info:
  title: Test management tool
  version: 0.1.0
paths:
  /api/v1/projects:
    $ref: './paths/projects.yaml'
  /api/v1/projects/{entityId}:
    $ref: './paths/project.yaml'
  /api/v1/projects/{entityId}/test-suite-root:
    $ref: './paths/projectTestSuiteRoot.yaml'
  /api/v1/test-cases:
    $ref: './paths/testCases.yaml'
  /api/v1/test-cases/{entityId}:
    $ref: './paths/testCase.yaml'
  /api/v1/test-cases/{entityId}/move:
    $ref: './paths/testCaseMove.yaml'
  /api/v1/test-cases/{testCaseId}/preconditions:
    $ref: './paths/testCasePreconditions.yaml'
  /api/v1/test-cases/{testCaseId}/steps:
    $ref: './paths/testCaseSteps.yaml'
  /api/v1/test-case-preconditions/{entityId}:
    $ref: './paths/testCasePrecondition.yaml'
  /api/v1/test-case-steps/{entityId}:
    $ref: './paths/testCaseStep.yaml'
  /api/v1/test-suites/{entityId}:
    $ref: './paths/testSuites.yaml'
  /api/v1/test-suites/{entityId}/leaves:
    $ref: './paths/testSuiteLeaves.yaml'
  /api/v1/test-suites/{entityId}/test-cases:
    $ref: './paths/testSuiteTestCases.yaml'
  /api/v1/test-suites/{entityId}/root-path:
    $ref: './paths/testSuiteRootPath.yaml'
  /api/v1/test-suites/{entityId}/get-project:
    $ref: './paths/testSuiteGetProject.yaml'
  /api/v1/test-suites/{entityId}/get-parent:
    $ref: './paths/testSuiteGetParent.yaml'
  /api/v1/auth/u-p/sign-in:
    $ref: './paths/auth/usernamePasswordSignIn.yaml'
