openapi: 3.0.3
info:
  title: Test management tool
  version: 0.1.0
paths:
  /api/v1/projects:
    $ref: './paths/projects.yaml'
  /api/v1/projects/{entityId}:
    $ref: './paths/project.yaml'
  /api/v1/projects/{entityId}/tree-root:
    $ref: './paths/projectTreeRoot.yaml'
  /api/v1/test-cases:
    $ref: './paths/testCases.yaml'
  /api/v1/test-cases/{entityId}:
    $ref: './paths/testCase.yaml'
  /api/v1/test-cases/{entityId}/move:
    $ref: './paths/testCaseMove.yaml'
  /api/v1/test-cases/{testCaseId}/preconditions:
    $ref: './paths/testCasePreconditions.yaml'
  /api/v1/test-cases/{testCaseId}/steps:
    $ref: './paths/testCaseSteps.yaml'
  /api/v1/test-case-preconditions/{entityId}:
    $ref: './paths/testCasePrecondition.yaml'
  /api/v1/test-case-steps/{entityId}:
    $ref: './paths/testCaseStep.yaml'
  /api/v1/trees/{entityId}:
    $ref: './paths/tree.yaml'
  /api/v1/trees/{entityId}/leaves:
    $ref: './paths/treeLeaves.yaml'
  /api/v1/trees/{entityId}/test-cases:
    $ref: './paths/treeTestCases.yaml'
  /api/v1/trees/{entityId}/root-path:
    $ref: './paths/treeRootPath.yaml'
