get:
  description: Get project information
  operationId: getProject
  tags:
    - Project
  parameters:
    - in: path
      name: entityId
      required: true
      schema:
        type: string
        format: uuid
  responses:
    '200':
      description: A JSON with project
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            required:
              - data
            properties:
              data:
                $ref: '../../schemas/project.yaml'
    '404':
      $ref: '../common/responses.yaml#/resourceNotFound'
    '500':
      $ref: '../common/responses.yaml#/internalServerError'
patch:
  description: Update new project
  operationId: updateProject
  tags:
    - Project
  parameters:
    - in: path
      name: entityId
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    content:
      application/json:
        schema:
          type: object
          additionalProperties: false
          properties:
            title:
              $ref: '../../schemas/project.yaml#/properties/title'
            description:
              $ref: '../../schemas/project.yaml#/properties/description'
  responses:
    '200':
      description: A JSON with project data
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              data:
                type: object
                additionalProperties: false
    '400':
      $ref: '../common/responses.yaml#/validationError'
