version: "3"
services:
  db:
    build: ./mssql
    user: root
    ports:
      - "1433:1433"
    volumes:
      - ./data/mssql-data:/var/opt/mssql/data
    networks:
      tc-network:
        ipv4_address: 172.20.0.4
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      tc-network:
        ipv4_address: 172.20.0.5
