version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pass --database=db --execute \"SHOW TABLES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      tc-network:
        ipv4_address: 172.20.0.4
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      tc-network:
        ipv4_address: 172.20.0.5
