version: "3"
services:
  backend:
    build:
      dockerfile: ./.docker/node/Dockerfile
      context: ../
    links:
      - db:db
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./../:/srv/backend-app
    networks:
      tc-network:
        ipv4_address: 172.20.0.3
networks:
  tc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.1/16
          gateway: 172.20.0.1
