type: object
required:
  - id
  - title
additionalProperties: false
properties:
  id:
    type: string
    description: Unique id
    format: uuid
  title:
    type: string
    description: Title
    minLength: 5
    maxLength: 255
  description:
    type: string
    description: Description
    maxLength: 5000
